"""Native, approval-gated Unreal Editor project discovery and Python execution."""
from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

from ..context import ToolContext
from ..errors import ToolExecutionError, ToolInputError
from ..permission_handler import PermissionResult
from ..permissions import maybe_ask_for_gated_tool
from ..protocol import ToolResult
from ..registry import ToolSpec


def discover_unreal_editors() -> list[str]:
    """Return installed command-line Unreal editors without requiring a plugin."""
    names = ("UnrealEditor-Cmd.exe", "UnrealEditor-Cmd")
    found: set[Path] = set()
    for name in names:
        candidate = shutil.which(name)
        if candidate:
            found.add(Path(candidate).resolve())
    if os.name == "nt":
        roots = [Path(value) for value in (os.environ.get("PROGRAMFILES"), os.environ.get("PROGRAMFILES(X86)")) if value]
        for root in roots:
            epic = root / "Epic Games"
            if epic.is_dir():
                found.update(path.resolve() for path in epic.glob("UE_*/Engine/Binaries/Win64/UnrealEditor-Cmd.exe"))
    return [str(path) for path in sorted(found)]


def _projects(root: Path) -> list[str]:
    return [str(path) for path in sorted(root.glob("**/*.uproject"))[:200] if ".git" not in path.parts]


def _project_summary(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ToolInputError(f"invalid Unreal project descriptor: {path}") from exc
    return {
        "path": str(path),
        "engine_association": payload.get("EngineAssociation"),
        "category": payload.get("Category"),
        "description": payload.get("Description"),
        "modules": payload.get("Modules") or [],
        "plugins": payload.get("Plugins") or [],
        "directories": {
            name: (path.parent / name).is_dir()
            for name in ("Config", "Content", "Plugins", "Source")
        },
    }


def _vector(value: Any, default: tuple[float, float, float]) -> tuple[float, float, float]:
    if isinstance(value, list) and len(value) == 3:
        try:
            return tuple(float(item) for item in value)  # type: ignore[return-value]
        except (TypeError, ValueError):
            pass
    return default


def _scene_script(actors: list[dict[str, Any]]) -> str:
    spec = []
    for index, item in enumerate(actors[:500]):
        spec.append({
            "name": str(item.get("name") or f"JonathanActor{index + 1}"),
            "class_path": str(item.get("class_path") or ""),
            "location": _vector(item.get("location"), (index * 150.0, 0.0, 0.0)),
            "rotation": _vector(item.get("rotation"), (0.0, 0.0, 0.0)),
            "scale": _vector(item.get("scale"), (1.0, 1.0, 1.0)),
        })
    encoded = json.dumps(spec, ensure_ascii=False)
    return f'''# Generated by Jonathan Ai. Review this project-scoped script before running it.
import json
import unreal

ACTORS = json.loads({json.dumps(encoded)})
actor_subsystem = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
created = []
for item in ACTORS:
    actor_class = unreal.load_class(None, item["class_path"]) if item["class_path"] else unreal.StaticMeshActor
    if not actor_class:
        raise RuntimeError("Unreal class not found: " + item["class_path"])
    actor = actor_subsystem.spawn_actor_from_class(
        actor_class,
        unreal.Vector(*item["location"]),
        unreal.Rotator(*item["rotation"]),
    )
    actor.set_actor_label(item["name"])
    actor.set_actor_scale3d(unreal.Vector(*item["scale"]))
    created.append(actor.get_path_name())
unreal.EditorLoadingAndSavingUtils.save_dirty_packages(True, True)
unreal.log("Jonathan Ai created " + str(len(created)) + " actors")
'''


class UnrealStudioTool:
    def spec(self) -> ToolSpec:
        return ToolSpec(
            name="UnrealStudio",
            description="Discover installed Unreal editors and .uproject files, inspect project descriptors, generate reviewable scene scripts, and run an approved existing Python script through UnrealEditor-Cmd. No hosted service or third-party MCP plugin is required.",
            input_schema={"type": "object", "additionalProperties": False, "properties": {
                "action": {"type": "string", "enum": ["status", "inspect_project", "generate_scene_script", "run_script"]},
                "project": {"type": "string"}, "script": {"type": "string"},
                "editor": {"type": "string"}, "output": {"type": "string"},
                "actors": {"type": "array", "maxItems": 500, "items": {"type": "object"}},
                "timeout": {"type": "integer", "minimum": 10, "maximum": 3600},
            }, "required": ["action"]},
            is_destructive=True,
            max_result_size_chars=80_000,
            strict=True,
        )

    def check_permissions(self, tool_input: dict[str, Any], context: ToolContext) -> PermissionResult:
        action = str(tool_input.get("action") or "")
        if action in {"status", "inspect_project"}:
            return PermissionResult.allow()
        verb = "write an Unreal scene script" if action == "generate_scene_script" else "run a reviewed Python script in Unreal Editor"
        return maybe_ask_for_gated_tool(context, "UnrealStudio", verb, "Allow Unreal Studio for the rest of this session")

    def run(self, tool_input: dict[str, Any], context: ToolContext) -> ToolResult:
        action = str(tool_input["action"])
        if action == "status":
            editors = discover_unreal_editors()
            return ToolResult(name="UnrealStudio", output={
                "ready": bool(editors), "editors": editors, "projects": _projects(context.workspace_root),
                "bridge": "Unreal Python command line", "plugin_required": False,
            })
        if action == "inspect_project":
            project = context.ensure_allowed_path(str(tool_input.get("project") or ""))
            if project.suffix.lower() != ".uproject" or not project.is_file():
                raise ToolInputError("project must be an existing .uproject file in an allowed directory")
            return ToolResult(name="UnrealStudio", output=_project_summary(project))
        if action == "generate_scene_script":
            output = context.ensure_allowed_path(str(tool_input.get("output") or "Saved/JonathanAi/scene.py"))
            if output.suffix.lower() != ".py":
                raise ToolInputError("output must be a .py file")
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(_scene_script(list(tool_input.get("actors") or [])), encoding="utf-8")
            artifacts = [context.artifact_publisher(output, output.name)] if context.artifact_publisher else []
            return ToolResult(name="UnrealStudio", output={"created": True, "script": str(output), "artifacts": artifacts})

        project = context.ensure_allowed_path(str(tool_input.get("project") or ""))
        script = context.ensure_allowed_path(str(tool_input.get("script") or ""))
        if project.suffix.lower() != ".uproject" or not project.is_file():
            raise ToolInputError("project must be an existing .uproject file in an allowed directory")
        if script.suffix.lower() != ".py" or not script.is_file():
            raise ToolInputError("script must be an existing .py file in an allowed directory")
        editor_value = str(tool_input.get("editor") or "")
        editors = discover_unreal_editors()
        editor = Path(editor_value).resolve() if editor_value else (Path(editors[-1]) if editors else None)
        if editor is None or not editor.is_file() or editor.name.lower() not in {"unrealeditor-cmd.exe", "unrealeditor-cmd"}:
            raise ToolInputError("UnrealEditor-Cmd was not found; install Unreal Engine or provide its exact editor path")
        command = [str(editor), str(project), f"-ExecutePythonScript={script}", "-unattended", "-nop4", "-nosplash"]
        try:
            completed = subprocess.run(command, cwd=project.parent, capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=int(tool_input.get("timeout") or 900), shell=False)
        except subprocess.TimeoutExpired as exc:
            raise ToolExecutionError("Unreal Editor script timed out") from exc
        output = (completed.stdout + "\n" + completed.stderr).strip()
        if completed.returncode:
            raise ToolExecutionError(f"Unreal Editor exited with code {completed.returncode}: {output[-8000:]}")
        return ToolResult(name="UnrealStudio", output={"ok": True, "returncode": completed.returncode, "command": command, "log": output[-40_000:]})
