from __future__ import annotations

from pathlib import Path

from .loader import load_tools_from_dir
from .registry import ToolRegistry
from .tools import (
    AskUserQuestionTool,
    AgentInstancesTool,
    AgentRosterTool,
    ArtifactTool,
    AudioStudioTool,
    BashTool,
    BriefTool,
    BusinessManagerTool,
    CodeMemoryTool,
    CharacterStudioTool,
    ContentReachTool,
    ConfigTool,
    CronCreateTool,
    CronDeleteTool,
    CronListTool,
    DeviceControlTool,
    DrawAiTool,
    ECCIntegrationTool,
    EnterPlanModeTool,
    EnterWorktreeTool,
    ExitPlanModeTool,
    ExitWorktreeTool,
    FileEditTool,
    FileReadTool,
    FileWriteTool,
    GlobTool,
    GrepTool,
    FinanceMarketsTool,
    FooocusTool,
    ImageStudioTool,
    VisionAnalyzeTool,
    LSPTool,
    KronosForecastTool,
    ListMcpResourcesTool,
    MCPTool,
    NotebookEditTool,
    PowerShellTool,
    PersonalFinanceVaultTool,
    ProcoderTool,
    PublicApiCatalogTool,
    REPLTool,
    RepositoryTool,
    ReadMcpResourceTool,
    RemoteTriggerTool,
    SendMessageTool,
    SendUserMessageTool,
    SharedMemoryTool,
    SpeechStudioTool,
    SkillTool,
    SkillManagerTool,
    SpawnWorkersTool,
    SleepTool,
    StructuredOutputTool,
    SystemAdminTool,
    TeamCreateTool,
    TeamDeleteTool,
    TaskCreateTool,
    TaskGetTool,
    TaskListTool,
    TaskOutputTool,
    TaskStopTool,
    TaskUpdateTool,
    TerminalTool,
    ThreeDStudioTool,
    TradingTool,
    UnrealStudioTool,
    TestingPermissionTool,
    TodoWriteTool,
    WebFetchTool,
    WebSearchTool,
)
from .tools.external_agent import ExternalAgentTool
from .tools.agent import AgentTool
from .tools.tool_search import ToolSearchTool


def build_default_registry(*, include_user_tools: bool = True) -> ToolRegistry:
    registry = ToolRegistry(
        tools=[
            SendUserMessageTool(),
            BashTool(),
            FileReadTool(),
            FileWriteTool(),
            FileEditTool(),
            GlobTool(),
            GrepTool(),
            WebFetchTool(),
            WebSearchTool(),
            SleepTool(),
            TaskStopTool(),
            ConfigTool(),
            MCPTool(),
            ExternalAgentTool(),
            ListMcpResourcesTool(),
            ReadMcpResourceTool(),
            LSPTool(),
            SkillTool(),
            SpawnWorkersTool(),
            AgentInstancesTool(),
            AgentRosterTool(),
            BriefTool(),
            AskUserQuestionTool(),
            TodoWriteTool(),
            TaskCreateTool(),
            TaskGetTool(),
            TaskListTool(),
            TaskUpdateTool(),
            TaskOutputTool(),
            TeamCreateTool(),
            TeamDeleteTool(),
            EnterPlanModeTool(),
            ExitPlanModeTool(),
            EnterWorktreeTool(),
            ExitWorktreeTool(),
            CronCreateTool(),
            CronListTool(),
            CronDeleteTool(),
            SendMessageTool(),
            StructuredOutputTool(),
            RemoteTriggerTool(),
            DeviceControlTool(),
            DrawAiTool(),
            ECCIntegrationTool(),
            TerminalTool(),
            PowerShellTool(),
            ArtifactTool(),
            AudioStudioTool(),
            ImageStudioTool(),
            VisionAnalyzeTool(),
            ThreeDStudioTool(),
            SystemAdminTool(),
            RepositoryTool(),
            SkillManagerTool(),
            SharedMemoryTool(),
            SpeechStudioTool(),
            BusinessManagerTool(),
            CodeMemoryTool(),
            CharacterStudioTool(),
            ContentReachTool(),
            FinanceMarketsTool(),
            FooocusTool(),
            TradingTool(),
            UnrealStudioTool(),
            KronosForecastTool(),
            PersonalFinanceVaultTool(),
            ProcoderTool(),
            PublicApiCatalogTool(),
            NotebookEditTool(),
            REPLTool(),
            TestingPermissionTool(),
        ]
    )
    registry.register(AgentTool(registry))
    registry.register(ToolSearchTool(registry))

    if include_user_tools:
        user_dir = Path.home() / ".clawd" / "tools"
        for tool in load_tools_from_dir(user_dir):
            registry.register(tool)

    return registry
